FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json
RUN npm ci
COPY . . 
RUN npm run build
RUN npm prune --production


FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production


COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY package.json package-lock.json next.config.js .


EXPOSE 3000

CMD ["npm", "run", "start"]